### ISSUE TITLE
Chapter 8: Importing weasyprint

### ISSUE THREAD

**Issue by bernarditoro** [PacktPublishing/Django-3-by-Example#102]
After modifying the admin.py of the order app to render html to pdf, and starting the server, I got this OSError:

_...
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'_

What could be the cause and possible solution?

**Comment by LanceMeister** [comment]
I am having the same issue as @bernarditoro I've tried pygobject but that doesn't work either.

**Comment by mkgiri1** [comment]
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

Try deploying the package and then uninstall and reinstall, I was having issues with weasyprint but

1. GTK-for-Windows-Runtime-Environment-Installer/releases (gtk3-runtime-3.24.29-2021-04-29-ts-win64.exe)
2. un-install and reinstall weasyprint  V51

**Comment by harryghgim** [comment]
@bernarditoro could this help? 

https://stackoverflow.com/a/70567247/11790764

I solved the issue by installing weasyprint package in my virtual env after I first installed some required packages with homebrew on mac.
