### ISSUE TITLE
Chapter 14 problem: No Course matches the given query.

### ISSUE THREAD

**Issue by yakotaki** [PacktPublishing/Django-3-by-Example#14]
after running python manage.py runserver
Im getting: 
June 26, 2020 - 14:22:33
Django version 3.0.7, using settings 'educa.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /
-----------------------------------
127.0.0.1:8000 shows :

Page not found (404)
Request Method: | GET
-- | --
http://127.0.0.1:8000/
courses.views.CourseListView

Any suggestions?

**Comment by LeonT-A** [comment]
You need to prove more info on where in the chapter you where, your OS, and what your code looks like. Too much going on to just guess where you might've made a mistake.

**Comment by yakotaki** [comment]
So, I'm trying to run Chapter 14 code, I did _python manage.py migrate_ , no errors. When I run _python manage.py runserver_ , I also don't see any errors, however i cannot open the web. The error I mentioned above appears.
django 3.0.7
python 3.6.8
windows 10

**Comment by LeonT-A** [comment]
Chapter 14 is 30 pages long. Saying you're running code isn't very helpful. Page number, some code, and when it stopped working?

**Comment by markpengisme** [comment]
If you run the server at `127.0.0.1` or `127.0.0.1:8000`,
you will cause an error on the code 
`course = get_object_or_404(Course, slug=host_parts[0])`
in the `subdomain_course_middleware` function(`middleware.py`)
