### ISSUE TITLE
[C4,P106] Found Typo in base.html

### ISSUE THREAD

**Issue by hazartilirot** [PacktPublishing/Django-3-by-Example#17]
The author asks his readers to add some lines into base.html when we use a build-in Django authentication log in and log out views: 

Here's the snippet of code in base.html, basically, you have to change:
Hello {{ request.user.**first_name**}}, to Hello {{ request.user.**username**}},

```
        <span class="user">
            {% if request.user.is_authenticated %}
                #Hello {{ request.user.first_name}}, # Typo.
                Hello {{ request.user.username}},
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </span>
```
![page106](https://user-images.githubusercontent.com/1349977/86029812-4f550f00-ba3c-11ea-9f3b-2d6382f118a1.png)

One won't get an error however it would be displayed "Hello, Logout". 

p.s. #page 107, typo in the following text: You display the user's **first name** and a link to log out if the user is authenticated, or a link to log in otherwise

**Comment by LeonT-A** [comment]
The code is valid, just your user has a blank [first_name](https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User.first_name) field. You could set it in the admin page. I didn't want to bother with adding first names to every test user, so yes I also replaced every occurrence of first_name with username.

 When the template renders and the field is blank, then nothing is inserted and it appears that the code failed.

**Comment by hazartilirot** [comment]
Yep, I know. You're correct. 
At this point the author should add a sentence that we need to go to admin and add first name OR 
generally speaking... it would be more obvious to show a username like GitHub does and many other websites.... 
username - is a field that can be used by default for that case. At least it can't be blank.

**Comment by zenx** [comment]
Thank you. I will add an explanation to fill in the user's first name using the Django admin site.
