### ISSUE TITLE
Getting a response error for zunionstore

### ISSUE THREAD

**Issue by Duke09** [PacktPublishing/Django-3-by-Example#18]
ResponseError at /en/cart/
wrong number of arguments for 'zunionstore' command

```
recommended_products = r.suggest_products_for(cart_products, max_results=4) 
```

```
r.zunionstore(tmp_key, keys) 
```

When a product is added to the cart its fine, but when there are no products in the cart or when we remove all the products from the cart it throws this error

**Comment by tolu-c** [comment]
I only get the error when I view an empty cart.
Tho I modified my cart_remove view, so I don't get the error when I removed cart items
