### ISSUE TITLE
User has no profile. I am getting this error when I am trying to run http://127.0.0.1:8000/account/edit/  

### ISSUE THREAD

**Issue by yasiriqbal1990** [PacktPublishing/Django-3-by-Example#19]
I am working on t chapter 4  section Extending the user model. I do not have any idea where profile from  profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)  is coming from. Moreover, when I tried to run it I am getting error User has no profile. I have followed each and every steps according to section Extending the user model.Please help. Thanks

**Comment by casualhuman** [comment]
Hy, you are getting User has no profile because you are trying to access that page probably with an account you create before creating the Profile model (maybe like a superuser account ) . Try signing up with a new user and check again. Hope that helps

**Comment by yasiriqbal1990** [comment]
Many thanks. It works.
