### ISSUE TITLE
How do I add User authentication in the website for checkouts and payments? and how do I save the Cart of the particular user because the cart app don't have any models??

### ISSUE THREAD

**Issue by jyotirani3020** [PacktPublishing/Django-3-by-Example#21]

**Comment by cforcross** [comment]
Check out this other github link
 https://github.com/codingforentrepreneurs/eCommerce/tree/master/src/carts
what you want has been implemented then..I am pretty sure you can then apply it to your project

**Comment by zenx** [comment]
The reference link provided bt @cforcross shows an example of how to persist cart data. Closing this issue because it's not an issue of the code examples of the book but a request about how to build additional functionality.
