### ISSUE TITLE
pagination chapter 1

### ISSUE THREAD

**Issue by azinsf7** [PacktPublishing/Django-3-by-Example#22]
hello,I have one problem
when I use class base view , It can't render page object. and in my template it goes like this:
Page of .
It doesn't work..
I checked my view It was the same with the book.

**Comment by DratutiYaVolkh** [comment]
Funny, had same issue. I think you need to create more posts. Next time feel free to upload your views and templates. :)

**Comment by azinsf7** [comment]
It was because I had 2 fucntions view for my url.I changed it and It worked

**Comment by DratutiYaVolkh** [comment]
Well done)

**Comment by alfonsovgs** [comment]
Or you can add elif in list.html for not show "Page of" without number.

{% if tag %}
    {% include "pagination.html" with page=posts %}
  {% elif page_obj %}
    {% include "pagination.html" with page=page_obj %}
  {% endif %}

**Comment by zenx** [comment]
Pagination is initially done with the `posts` temaplate variable passed in the `post_list` view:
```
{% include "pagination.html" with page=posts %}
```
Then,  `page_obj` is used when the post list view is replaced by a class-based view using `ListView`:
```
{% include "pagination.html" with page=page_obj %}
```

**Comment by canahmet98** [comment]
ı'm taking error when ı clicked next is it normal?
