### ISSUE TITLE
Wrong CSS files for Chapter 7

### ISSUE THREAD

**Issue by calvinchiulele** [PacktPublishing/Django-3-by-Example#31]
The CSS files included in chapter 7 in this code don't conform to the ones shown in the images examples from the book. The CSS files present in the code for Chapter 7 are the same used in Chapters 5 and 6.

Could I have the CSS files for Chapter 7?

**Comment by vivekthedev** [comment]
> The CSS files included in chapter 7 in this code don't conform to the ones shown in the images examples from the book. The CSS files present in the code for Chapter 7 are the same used in Chapters 5 and 6.
> 
> Could I have the CSS files for Chapter 7?

Right I am facing this problem too
