### ISSUE TITLE
cd variable in Bookmarks

### ISSUE THREAD

**Issue by dusty5213** [PacktPublishing/Django-3-by-Example#37]
There is a cd variable assigned in bookmarks/images/views.py but never used. Is there any reason for it???

**Comment by njugunapm233** [comment]
Data cleaning

Regards Peter Njuguna

**Comment by SPH73** [comment]
@dusty5213 each form has a cleaned_data attribute. When you call ```is-Valid()```  on the form data, it is placed into the cleaned_data attribute; which we then assigned to variable named 'cd' and then we could check the values of each of the keys (form fields) i.e cd['password'] or cd['username'].

**Comment by SPH73** [comment]
@dusty5213 I see the cd you are referring to. It isn't used as far as I can see either and the only other place cleaned_data is in the form to access the url from.  The cd variable comes after that anyway in the view and not via the cd variable.

I hope we can get an explanation for this.

**Comment by zenx** [comment]
@SPH73 you are right, this line is not needed. Fixed in https://github.com/PacktPublishing/Django-3-by-Example/commit/2ccbbab68722a53ba31e90c43c7a8908053123b8

Thank you!
