### ISSUE TITLE
Chapter 4 base.html 

### ISSUE THREAD

**Issue by SPH73** [PacktPublishing/Django-3-by-Example#39]
In my base.html the {% if section... class='selected' i the li tags has no effect and the item doesn't get highlighted. However, it seems that my editor has an issue with the logic being placed inside of li particularly each of the == has different syntax highlighting. I changed quotes to single to see if that made a difference and I copied the code in the source code and again, no difference.
![image](https://user-images.githubusercontent.com/48051095/95462288-34fdcc00-096f-11eb-90b9-b3584ba431c2.png)

**Comment by SPH73** [comment]
![image](https://user-images.githubusercontent.com/48051095/95462530-87d78380-096f-11eb-839f-77b5635921f6.png)
Even with single quotes...

**Comment by SPH73** [comment]
![image](https://user-images.githubusercontent.com/48051095/95462679-ba817c00-096f-11eb-9d86-7a623dcee03d.png)
This is how it renders regardless.

**Comment by jrdjango** [comment]
Is it possible that the section variable is not defined?

**Comment by SPH73** [comment]
You mean in the context?
![image](https://user-images.githubusercontent.com/48051095/95675680-e2135700-0bb0-11eb-8d79-2f84af7d8798.png)

**Comment by SPH73** [comment]
Thank you @jrdjango it is the 'dashboard' missing the quotation marks around it! :) I didn't spot it until I posted it in reply.
