### ISSUE TITLE
Password Resetting view displays the django framework template - Chapter )4

### ISSUE THREAD

**Issue by tolu-c** [PacktPublishing/Django-3-by-Example#51]
Even after adding template name in my urls.py, I still don't get any improvement

```
from django.urls import path
from .views import UserRegisterView, AddProductView, CategoryView, UserEditView, PasswordsChangeView
from django.contrib.auth import views as auth_views
from . import views
from .views import *

app_name = 'members'

urlpatterns = [
    # path('signup/', UserRegisterView.as_view(), name='signup'),
    # path('account/', UserEditView.as_view(), name='edit_account'),
    path('account/', views.edit, name='edit_account'),
    path('signup/', views.signup, name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    # path('password/', auth_views.PasswordChangeView.as_view(template_name='registration/change_password.html')),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change_password.html'), name='password'),
    path('add_product/', AddProductView.as_view(), name='add_product'),
    path('add_category/', CategoryView.as_view(), name='add_category'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]
```
It only works for this `path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),`
Thanks for your help

**Comment by Alex-Wait-For-It-Wolf** [comment]
Can you describe issue more concrete, what exactly doesn't work?

**Comment by tolu-c** [comment]
the urls are working, but it shows the django template instead of the base.html template.
i don't know why I can't upload images

**Comment by MagereMagere** [comment]
Since your reset template is hosted in your registration folder, you need to make your changes from there.
Import your statics into it.

**Comment by Alex-Wait-For-It-Wolf** [comment]
Here is my urls.py of account app

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # post views
    # previous login view
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    # Change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # Reset password urls
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
         
    path('register/', views.register, name='register'),
    
    path('edit/', views.edit, name='edit'),
    
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

if your base.html doesn't work, maybe it's because of location, it should be account\templates\base.html
if your other templates can't see base.html maybe you forget to insert {% extends "base.html" %} at the start of each of your templates
maybe you need to change location of your password reset templates to templates\registration\ (it's default location, if you change it, then you will need change views too, for now it's not worth it, just stick to the manual)
