### ISSUE TITLE
Blog - get_absolute_url missing one "/"

### ISSUE THREAD

**Issue by OmidShojaee** [PacktPublishing/Django-3-by-Example#53]
Hello,

get_absolute_url generates the link as "2020/12/9slug" not "2020/12/9/slug".

How to add the missing "/"?

**Comment by MagereMagere** [comment]
> Hello,
> 
> 
> 
> get_absolute_url generates the link as "2020/12/9slug" not "2020/12/9/slug".
> 
> 
> 
> How to add the missing "/"?

In the url file append a / after the path

**Comment by zenx** [comment]
The path defined in [urls.py](https://github.com/PacktPublishing/Django-3-by-Example/blob/master/Chapter01/mysite/blog/urls.py) is well defined: `path('<int:year>/<int:month>/<int:day>/<slug:post>/' ... )`
