### ISSUE TITLE
Chapter12/educa/courses/templates/courses/content/image.html

### ISSUE THREAD

**Issue by AmoahDevLabs** [PacktPublishing/Django-3-by-Example#57]
** ### `<p><img src="{{ item.file.url }}" alt="{{ item.title }}"></p>` ** not displaying image.

**Fixing**: 
** `<p><img src="{{ item.image.url }}" alt="{{ item.title }}"></p>` ** - This now displays the image.

**Comment by zenx** [comment]
The field of the `Image` model used to store the image file is named `file`. See [models.py](https://github.com/PacktPublishing/Django-3-by-Example/blob/master/Chapter12/educa/courses/models.py). @AmoahDevLabs maybe you named the field `image`?

**Comment by AmoahDevLabs** [comment]
Alright thank
