### ISSUE TITLE
Chapter 1: Django isn't finding css file, Ubuntu 20.10

### ISSUE THREAD

**Issue by UltraBurstXD** [PacktPublishing/Django-3-by-Example#64]
Hi,
I'm having trouble finding CSS file and my blog site looks like this:
![Screenshot from 2021-02-13 17-22-57](https://user-images.githubusercontent.com/55871338/107853712-298c4700-6e20-11eb-8cec-38c1beea7115.png)

I've followed everything in book and based my project structure in this repo.

**Comment by shubham-0K** [comment]
You are viewing "http://127.0.0.1:8000/**admin/blog/**", instead of "http://127.0.0.1:8000/**blog/**".
(Also make sure that '**blog.css**' is located at '**/blog/static/css/**'.)

**Comment by shubham-0K** [comment]
You are viewing "http://127.0.0.1:8000/**admin/blog/**", instead of "http://127.0.0.1:8000/**blog/**".
(Also make sure that 'blog.css' is located at '/blog/static/css/'.)

**Comment by shubham-0K** [comment]
You are viewing "http://127.0.0.1:8000/admin/blog/" instead of "http://127.0.0.1:8000/blog/".
(Also make sure that 'blog.css' is located at '/blog/static/css/'.)

**Comment by UltraBurstXD** [comment]
> You are viewing "http://127.0.0.1:8000/admin/blog/" instead of "http://127.0.0.1:8000/blog/".
> (Also make sure that 'blog.css' is located at '/blog/static/css/'.)

Oh... I see. I'll try do that.
