### ISSUE TITLE
Chapter 7:  for ' cart_detail' not found. ' cart_detail' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by ziom1555** [PacktPublishing/Django-3-by-Example#69]
![error](https://user-images.githubusercontent.com/65669121/109806960-9a579f80-7c25-11eb-9d31-081b4097e93e.png)

my base.html:
`{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Mój sklep{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">Mój sklep</a>
    </div>
    <div id="subheader">
      <div class="cart">
       {% with total_items=cart|length %}
         {% if cart|length > 0 %}
           Koszyk:
            <a href="{% url "cart: cart_detail" %}">
              {{ total_items }} produkt{{ total_items|pluralize}},
              {{ cart.get_total_price }} zł </a>
         {% else %}
           Koszyk jest pusty.
         {% endif %}
         {% endwith %}
      </div>
      <div id="content">
          {% block content %}
        {% endblock %}
      </div>
  </body>
</html>`

cart/urls:
`from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]`

cart/detail:
`{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Koszyk na zakupy
{% endblock %}

{% block content %}
  <h1>Koszyk na zakupy</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Obraz</th>
        <th>Produkt</th>
        <th>Ilość</th>
        <th>Usuń</th>
        <th>Cena jednostkowa</th>
        <th>Kwota</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Zmień">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Usuń</a></td>
            <td class="num">{{ item.price }} zł</td>
            <td class="num">{{ item.total_price }} zł</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Wartość całkowita</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} zł</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button
    light">Kontynuuj zakupy</a>
    <a href="#" class="button">Do kasy</a>
  </p>
{% endblock %}`

cart/views.py:
`from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                    'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})`

Does anyone know how to fix this error?

**Comment by ziom1555** [comment]
I solved the problem.
In the base.html file, I had spaces in the line:

```
<a href=" replies "cart: cart_detail"% inc">
after the word "cart:"

```
Correct spelling without spaces. There must be no spaces after the word "cart:". Correct ruler:

`<a href=" replies "cart: cart_detail"% inc">`

**Comment by zenx** [comment]
Exactly, there should be no spaces in `cart:cart_detail`. The code should look like this:
```
<a href="{% url "cart:cart_detail" %}">
    {{ total_items }} item{{ total_items|pluralize }},
    ${{ cart.get_total_price }}
</a>
```
