### ISSUE TITLE
Chapter 5 - URL with Django and Duke image

### ISSUE THREAD

**Issue by drozdzu88** [PacktPublishing/Django-3-by-Example#70]
Hi, 
I've started chapter 5 and I created first models, views etc. 
Last thing is adding image by URL in browser, but I'm using paper book and don't know what sign is before "url" in  URL adress. 
Can anyone copy and paste link from e-book version for me ? :)

**Comment by zenx** [comment]
Hi @drozdzu88, I think you are referring to the following URL:

```
https://127.0.0.1:8000/images/create/?title=%20Django%20and%20Duke&url=https://upload.wikimedia.org/wikipedia/commons/8/85/Django_Reinhardt_and_Duke_Ellington_%28Gottlieb%29.jpg
```
