### ISSUE TITLE
Chapter 4

### ISSUE THREAD

**Issue by Labasa** [PacktPublishing/Django-3-by-Example#85]
How do I fix this problem? Please, someone help. First, it is not possible to disable "Use Strict Mode for Redirect Urls". Second, I  am getting error when I try to use Facebook to login. I have Attached the screenshots below.
![Screenshot (470)](https://user-images.githubusercontent.com/46225052/119936957-a6d46580-bf92-11eb-9798-f1fa2639200d.png)
![Screenshot (469)_LI](https://user-images.githubusercontent.com/46225052/119937036-cbc8d880-bf92-11eb-84e8-936fbf2b5fdf.jpg)

**Comment by Labasa** [comment]
Thank you. I managed to solve the problem.

**Comment by timotif** [comment]
I'm exactly in your situation: how did you solve this?
